Localization support for India
appknox/website pull request #149
Opened 2017-04-10 08:45 UTC by yashwin

fixes #146

2017-04-10 08:50 UTC, subho007 requested changes

2017-04-10 08:50 UTC, subho007 commented on _includes/js_footer.html
> +<script language="JavaScript" src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
we only use https not http @yashwin the test should have failed

2017-04-10 08:53 UTC, yashwin commented on _includes/js_footer.html
> +<script language="JavaScript" src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
Sorry, my bad. The test should've failed, but it dint

2017-04-11 05:59 UTC, subho007 approved these changes

2017-04-11 06:03 UTC, merged