APIT section & Product menu
appknox/website pull request #254
Opened 2019-02-14 06:12 UTC by yashwin

2019-02-14 06:12 UTC, subho007 commented on _assets/js/main.js
> +      ev.preventDefault;
__[JSHint]__ Expected an assignment or function call and instead saw an expression.

<sub>posted by Sider</sub>

2019-02-14 06:12 UTC, subho007 commented on _assets/js/main.js
> +  })
__[JSHint]__ Missing semicolon.

<sub>posted by Sider</sub>

2019-02-15 10:26 UTC, subho007 requested changes

2019-02-15 10:26 UTC, subho007 commented on _assets/css/main.css
> +  margin-top: -2em!important;
I hate `!important` @cosmosgenius @Praseetha-KR thoughts?

2019-02-15 10:36 UTC, cosmosgenius commented on _assets/css/main.css
> +  margin-top: -2em!important;
if possible remove!

2019-02-15 11:11 UTC, yashwin commented on _assets/css/main.css
> +  margin-top: -2em!important;
oh shit, removed it 👍

2019-02-15 19:11 UTC, subho007 approved these changes

2019-02-15 19:12 UTC, merged